### ISSUE TITLE
manipulate() and locator()/identify() interoperability bug 

### ISSUE THREAD

**Issue by daviesbj** [rstudio/manipulate#2]
I'm QC-ing a large dataset using `RStudio`. I'm viewing chunks of it using a graphics montage made using regular R graphics, with some `manipulate()` controls to control the subsetting. When I see something funny on a display, I want to pick some XY coordinate pairs (NOT data points, but in the same space), hit the `Finish` button provided by `locator()` to capture my picks, then go back to browsing. In this way I am building up a set of picked XY locations for further processing.

So my `manipulate()` controls are mostly subsetting parameters, but I also have a button called `Pick Points` to enter `locator()` mode.

This almost works, but when I hit `Finish` to terminate `locator()`, things don't quite work right. `locator()` finishes and returns a list of coordinate arrays as expected, but the graphics display stays in `locator()` crosshair mode and the `Finish` button persists. Any further clicks or `Finish` button clicks provoke an error popup `Method not found`.

I can right-mouse on the graph and `Reload` to reset things without hurting the running program or my saved data, but it's a bit distracting.

Here's a minimal example that provokes the bug. 

```
demonstrateBug <- function() {
manipulate(
  {
    if( pickData ){
      locData <- locator()
      nPoint <- length( locData$x )
      message( " ... Picked ", nPoint, " points" )
    } else {
      plot( runif(10), runif(10) )
    }
  },
  pickData = button("Pick Points")
)
}
```

I modified the above snippet to use `identify()` instead of `locator()` and the same thing happened.

I've tried Google but there are very few references to the specific combination of `manipulate()` and `locator()`, and nothing about a bug like this.

`locator()` works OK from the RStudio console when run against a `manipulate()`-enhanced graphics plot, but that won't do what I want.

If I give `locator()` a fixed number of points, it returns on cue, but the cross-hairs and button still persist. I don't want a fixed number of points, anyway. 

This bug has been reproduced on the following platforms:
- R 3.1.2 RStudio 0.99.441 on OSX Yosemite
- 0.99.441 on Fedora (R version unknown)
- R 3.1.2 RStudio 0.98.1091 on Windows 7

Originally reported at http://stackoverflow.com/questions/30583832/rstudio-graphics-locator-gets-stuck-under-manipulate which I will now close.

**Comment by jjallaire** [comment]
Unfortunately `manipulate` and `locator` don't play well together so this is known/expected behavior.

**Comment by daviesbj** [comment]
Dang. OK, thanks for letting me know.
